"""
Vocabulary Generation Script

Automatically derives two artifacts from the policy sources at ingestion time:

  1. policies/predicate_signatures.json
     — Input predicate names, arities, and argument names parsed from the
       @input markers in holiday_policy.lp.
     — Used by fact_extractor.py to build EXTRACTION_PROMPT dynamically.

  2. policies/vocabulary_map.json
     — Key policy terms mapped to common user paraphrases.
     — Generated by asking Haiku to analyze the ChromaDB chunks once.
     — Used by query_rewriter.py to build _VOCAB_HINT dynamically.

Both files fall back gracefully: if missing, the agents use their hardcoded
defaults. After any re-ingestion, run this script (or ingest_policy.py which
calls it automatically) to keep the files in sync with the current policy.

Usage:
    python scripts/generate_vocabulary.py
"""

import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dotenv import load_dotenv

load_dotenv()

LP_PATH     = Path("policies/holiday_policy.lp")
SIG_PATH    = Path("policies/predicate_signatures.json")
VOCAB_PATH  = Path("policies/vocabulary_map.json")

# Matches lines like:
#   % @input  age/2  CustID Age  # Customer age (integer years)
_INPUT_RE = re.compile(
    r"^%\s+@input\s+(\w+)/(\d+)\s+([\w\s]+?)(?:\s*#\s*(.*))?$"
)


# ── Step 1: Extract predicates from Clingo file ───────────────────────────────

def extract_predicates(lp_path: Path = LP_PATH) -> list[dict]:
    """Parse @input markers from holiday_policy.lp."""
    predicates = []
    for line in lp_path.read_text(encoding="utf-8").splitlines():
        m = _INPUT_RE.match(line.strip())
        if m:
            name, arity, args_str, desc = m.groups()
            args = args_str.strip().split()
            predicates.append({
                "name":        name,
                "arity":       int(arity),
                "args":        args,
                "description": (desc or "").strip(),
            })
    return predicates


# ── Step 2: Generate vocabulary map via LLM ───────────────────────────────────

_VOCAB_GEN_SYSTEM = """You are a terminology analyst for a holiday booking compliance system.

Given policy document chunks, extract key domain-specific terms and for each term
list the 3–5 most common ways a customer (non-expert) would paraphrase it.

Output ONLY valid JSON in this exact format — no markdown, no explanation:
{
  "terms": {
    "<policy term>": ["<paraphrase 1>", "<paraphrase 2>", "<paraphrase 3>"],
    ...
  }
}

Focus on terms that:
- Have a fixed technical meaning in the policy (fees, deadlines, rule names)
- Are often expressed differently by customers (colloquial vs. legal)
- Are critical for retrieval (missing the right term = wrong chunk retrieved)

Extract 12–20 terms. Include: lead name, amendment fee, cancellation fee, deposit,
84 days, ATOL, ABTA, minor, adult companion, complaint deadline, injury claim.
"""


def generate_vocab_map(chunks: list[str]) -> dict:
    """Call Haiku to generate vocabulary mappings from policy chunks."""
    from langchain_aws import ChatBedrock
    from langchain_core.messages import HumanMessage, SystemMessage

    llm = ChatBedrock(
        model_id=os.getenv(
            "BEDROCK_REWRITER_LLM",
            "eu.anthropic.claude-haiku-4-5-20251001-v1:0",
        ),
        region_name=os.getenv("AWS_DEFAULT_REGION", "eu-central-1"),
        credentials_profile_name=os.getenv("AWS_PROFILE", "default"),
        model_kwargs={"temperature": 0, "max_tokens": 1500},
    )

    # Use first 10 chunks (enough to cover the full policy, stay under token limit)
    sample = "\n\n---\n\n".join(chunks[:10])
    response = llm.invoke([
        SystemMessage(content=_VOCAB_GEN_SYSTEM),
        HumanMessage(content=f"POLICY CHUNKS:\n\n{sample}"),
    ])

    raw = response.content.strip()
    # Strip markdown code fences if present
    if raw.startswith("```"):
        raw = re.sub(r"^```[a-z]*\n?", "", raw)
        raw = re.sub(r"\n?```$", "", raw)

    return json.loads(raw)


# ── Main entry point ──────────────────────────────────────────────────────────

def generate_vocabulary(
    lp_path: Path = LP_PATH,
    sig_path: Path = SIG_PATH,
    vocab_path: Path = VOCAB_PATH,
) -> tuple[int, int]:
    """
    Generate both JSON artifacts. Returns (predicate_count, vocab_term_count).
    Called automatically by ingest_policy.py after ingestion.
    """
    sig_path.parent.mkdir(parents=True, exist_ok=True)

    # ── 1. Predicate signatures from Clingo ──────────────────────────────────
    predicates = extract_predicates(lp_path)
    sig_path.write_text(
        json.dumps({"predicates": predicates}, indent=2),
        encoding="utf-8",
    )
    print(f"[vocab] Saved {len(predicates)} predicate signatures → {sig_path}")

    # ── 2. Vocabulary map from ChromaDB chunks ───────────────────────────────
    try:
        from src.ingestion.policy_ingestor import get_vectorstore
        backend = os.getenv("EMBEDDING_BACKEND", "huggingface")
        # Try bedrock first for richer vocabulary generation, fall back to HF
        for b in [backend, "bedrock", "huggingface"]:
            try:
                vs = get_vectorstore(backend=b)
                results = vs.similarity_search("policy terms fees cancellation amendment", k=20)
                chunks = [doc.page_content for doc in results]
                if chunks:
                    break
            except Exception:
                chunks = []

        if not chunks:
            raise RuntimeError("Could not retrieve chunks from any ChromaDB collection.")

        vocab_data = generate_vocab_map(chunks)
        vocab_path.write_text(
            json.dumps(vocab_data, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        term_count = len(vocab_data.get("terms", {}))
        print(f"[vocab] Saved {term_count} vocabulary mappings → {vocab_path}")
    except Exception as exc:
        print(f"[vocab] Vocabulary map generation failed (non-fatal): {exc}")
        term_count = 0

    return len(predicates), term_count


if __name__ == "__main__":
    n_pred, n_vocab = generate_vocabulary()
    print(f"\nDone: {n_pred} predicates, {n_vocab} vocabulary terms.")
