"""
Fact Extraction Agent

Converts CLAIM: lines from the RAG agent's output into valid ASP ground atoms.
Also reports UNMAPPED: lines for claims that cannot be translated to any predicate
— these trigger partial_validation=True, which causes the decision node to escalate
rather than approve.

Predicate list is loaded dynamically from policies/predicate_signatures.json
(generated by scripts/generate_vocabulary.py during ingestion). Falls back to
the hardcoded 13-predicate list if the file is not found.
"""

import json
import os
import re
from pathlib import Path

from dotenv import load_dotenv
from langchain_aws import ChatBedrock
from langchain_core.messages import HumanMessage

from src.state import GuardrailsState
from src.telemetry import node, set_span_attrs
from src.pipeline_logger import log_extractor

load_dotenv()

# ── Hardcoded fallback predicates (used when predicate_signatures.json absent) ─

_FALLBACK_PREDICATES = [
    "  customer(CustID).",
    "  booking(CustID, BookID).",
    "  age(CustID, Age).",
    "  has_adult_companion(CustID).",
    "  days_until_holiday(BookID, Days).",
    "  paid_full(CustID, BookID).",
    "  includes_flight(BookID).",
    "  complaint_filed_days(CustID, BookID, Days).",
    "  injury_claim_filed_days(CustID, BookID, Days).",
    "  llm_approves_booking(CustID, BookID).",
    "  llm_rejects_booking(CustID, BookID).",
    "  llm_claims_cancellation_fee(CustID, BookID, Percent).",
    "  llm_claims_fee(CustID, BookID, FeeType, AmountPence).",
]


def _load_predicate_block() -> str:
    """Return the predicate list as a formatted string for the prompt."""
    sig_path = Path("policies/predicate_signatures.json")
    if sig_path.exists():
        try:
            data = json.loads(sig_path.read_text(encoding="utf-8"))
            preds = data.get("predicates", [])
            if preds:
                lines = []
                for p in preds:
                    args = ", ".join(p["args"])
                    lines.append(f"  {p['name']}({args}).")
                return "\n".join(lines)
        except Exception:
            pass
    return "\n".join(_FALLBACK_PREDICATES)


# ── Prompt template (predicates injected at load time) ────────────────────────

_PROMPT_TEMPLATE = """Convert these natural language claims into ASP facts for the Clingo solver.

USE ONLY THESE PREDICATES:

{predicates}

FORMATTING RULES:
1. One fact per line, ending with a period.
2. Use "c1" for customer ID and "b1" for booking ID unless the claims
   mention specific IDs.
3. Money values must be in pence (£25 = 2500, £50 = 5000).
4. Percentages must be integers (30, not 0.3).
5. FeeType options: "name_change", "upgrade_service",
   "change_duration", "change_accommodation".

OUTPUT CONSTRAINT:
- Output ONLY valid ASP ground facts and UNMAPPED lines, nothing else.
- No comments, no explanations, no markdown formatting, no backticks.
- ALL arguments must be GROUND (quoted strings or integers). NEVER use variable
  names like CustID, BookID, Age, Days as arguments — use "c1" and "b1" as defaults.
- If a claim CAN be mapped to a predicate: output the ASP fact.
- If a claim CANNOT be mapped to any predicate: output exactly:
  UNMAPPED: <original claim text>
- If NO claim maps to any predicate, output: NO_FACTS

CLAIMS TO CONVERT:
{{claims}}

ASP FACTS:"""

# Build once at module load (refreshed if file changes)
EXTRACTION_PROMPT = _PROMPT_TEMPLATE.format(predicates=_load_predicate_block())

# ── Validation regex: ground ASP fact (lowercase predicate, quoted/int args) ──

FACT_PATTERN = re.compile(
    r'^[a-z][a-z_]*\('
    r'("[^"]*"|\d+)'
    r'(,\s*("[^"]*"|\d+))*'
    r'\)\.$'
)

# ── Singleton LLM ─────────────────────────────────────────────────────────────

_llm = None


def _get_llm():
    global _llm
    if _llm is None:
        # ISS-003: No credentials_profile_name — use env vars (AWS_ACCESS_KEY_ID etc.)
        _llm = ChatBedrock(
            model_id=os.getenv("BEDROCK_LLM", "eu.anthropic.claude-sonnet-4-6"),
            region_name=os.getenv("AWS_DEFAULT_REGION", "eu-central-1"),
            model_kwargs={"temperature": 0, "max_tokens": 800},
        )
    return _llm


# ── Node ──────────────────────────────────────────────────────────────────────

@node("fact_extractor")
def fact_extraction_agent_node(state: GuardrailsState) -> dict:
    """
    Convert CLAIM: lines to ASP atoms and track unmappable claims.

    Reads:  state["llm_answer"]
    Writes: extracted_claims, extracted_facts, unextractable_claims, partial_validation
    """
    answer = state.get("llm_answer", "")

    claims = [
        line.strip()[len("CLAIM:"):].strip()
        for line in answer.splitlines()
        if line.strip().startswith("CLAIM:")
    ]

    if not claims:
        return {
            "extracted_claims":    [],
            "extracted_facts":     [],
            "unextractable_claims": [],
            "partial_validation":  False,
        }

    llm = _get_llm()
    prompt = EXTRACTION_PROMPT.format(claims="\n".join(f"- {c}" for c in claims))
    response = llm.invoke([HumanMessage(content=prompt)])

    valid_facts: list[str] = []
    unextractable: list[str] = []

    for line in response.content.strip().splitlines():
        line = line.strip().strip("`")
        if line.startswith("UNMAPPED:"):
            claim_text = line[len("UNMAPPED:"):].strip()
            if claim_text:
                unextractable.append(claim_text)
        elif FACT_PATTERN.match(line):
            valid_facts.append(line)
        # NO_FACTS and blank lines are silently skipped

    partial = len(unextractable) > 0

    log_extractor(claims, valid_facts)
    set_span_attrs({
        "extractor.claims_in":            len(claims),
        "extractor.facts_out":            len(valid_facts),
        "extractor.unextractable_count":  len(unextractable),
        "extractor.unextractable_claims": unextractable[:3],
        "extractor.llm_output_length":    len(response.content),
    })

    return {
        "extracted_claims":    claims,
        "extracted_facts":     valid_facts,
        "unextractable_claims": unextractable,
        "partial_validation":  partial,
    }
